FROM rust:latest

COPY cargo-config /usr/local/cargo/config

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y libc6-armhf-cross libc6-dev-armhf-cross gcc-arm-linux-gnueabihf && \
    apt-get install -y libdbus-1-dev libdbus-1-dev:armhf  && \
    apt-get clean && \
    rustup target add armv7-unknown-linux-gnueabihf
